### ISSUE TITLE
Modernization of TC repo

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#194]
We have been having some discussions to modernize the TC codebase. Here are the proposed changes:

- [x] ~Create a top level 'tc' folder, create tc/proto and move .proto files there. They should be included as tc/proto/mapping_options.pb.h~ done in #279 
- [x] ~Move subfolders of include/tc into tc/ and same for subfolders of src/~ done in #279 
    - Use best judgement for merging some of those folders if it makes sense
    - This should be synced with other big PRs that might be in progress
- [x] ~supply -WError in dev builds and in CI. Make sure that errors Mingzhe Li fixed for various virtual destructors trigger errors in OSS build as well~ done in #284  

cc @salexspb

**Comment by prigoyal** [comment]
Hi TC team: @skimo-openhub , @ttheodor , @ftynse , @nicolasvasilache , @abadams , @zdevito 

as we have been discussing this over VC and have concluded to most things, I created this issue to track the progress as I work on this. I would love to hear comments from you all on this.

**Comment by nicolasvasilache** [comment]
nice summary, thanks!
looks good to me.
Let's just hold off until pr/decouple-cuda is sent for review and lands otherwise merge conflicts will be massive.

**Comment by prigoyal** [comment]
thank you @nicolasvasilache for the review. Do we have an ETA on pr/decouple-cuda for when it is expected to land? :) cc @salexspb

**Comment by nicolasvasilache** [comment]
I'm cutting a large commit into smaller ones as we speak, it will prob require a few rounds of review but hopefully will land soon.

**Comment by ftynse** [comment]
I also prefer #149 and #161 to land.  Otherwise I will feel like abandoning those PRs.

**Comment by nicolasvasilache** [comment]
@skimo-openhub absolutely, the circular dependence should be a non-problem and an indication of code-smell. We should ensure we use TensorComprehensions.h internally and that will probably require refactorings (e.g. we probably should not expose the functionality from ```core/cuda/cuda.h``` at any time in ```TensorComprehensions.h ``` or we'll have to start including ```#ifdef``` spaghetti; ideally we'd avoid that unless absolutely necessary).

**Comment by salexspb** [comment]
I am bit confused about TensorComprehensions.h causing circular deps if it just does includes of private code. 

On a separate note - what is the evidence that it is needed? I tried to find example of modern codebases with large external community. PyTorch is not good example as it was mainly focused on Python.

How about TensorFlow? Here is their c++ API intro: https://www.tensorflow.org/api_guides/cc/guide
There is no TensorFlow.h that one has to include. Instead public API is still just normal header files.

What is our goal here? If we want to hide private API, why not just put functions into private namespace or even a folder?

**Comment by skimo-openhub** [comment]
On Fri, Mar 23, 2018 at 05:34:18PM -0700, Alexander Sidorov wrote:
> I am bit confused about TensorComprehensions.h causing circular deps if it just does includes of private code. 
> 
> On a separate note - what is the evidence that it is needed?

It shoudn't be needed.  The private headers should include
the public header and not the other way around.

skimo

**Comment by nicolasvasilache** [comment]
> I am bit confused about TensorComprehensions.h causing circular deps if it just does includes of private code.
> On a separate note - what is the evidence that it is needed? 

@salexspb I seem to remember you proposed ```TensorComprehensions.h``` during our discussion based on ```Halide.h``` and that you mentioned circular dependencies and I think the list above reflects the discussion we had; we can certainly drop that.

Personally, AFAIC there is no public C++ API at. We can grow one incrementally as needed. The first candidates are what is needed to write and run tests and examples, in particular the functionality that is exposed via pybind.

I can give this a first stab once #197 is merged.

**Comment by prigoyal** [comment]
Hello everyone, thanks for the discussion. It seems like on `TensorComprehensions.h` we are still undecided if this is the right way to go. @salexspb, I was wondering if this is required for fbcode or perhaps not? 

@ftynse , @nicolasvasilache I also wanted to do a friendly ping on #197, #149, #161 on the ETA for their merge as I and @salexspb were both wondering. This would allow better prioritization and timeline for when I can start working on the modernization tasks listed here. Thanks so much :)

**Comment by nicolasvasilache** [comment]
#149 and #161 I plan to merge today
#197 needs a review

**Comment by salexspb** [comment]
TensorComprehensions.h is not required in FBCode and probably won't be used even if it exists. 

In fact this was more a compromise for a raised by somebody issue about having .cc and .h together - people will have more files they see when looking for includes :) As I mentioned above, this doesn't seem to be a huge issue in my view. Good documentation and examples address an issue of "which headers should I include?", TensorFlow c++ API is an example here.

Splitting headers and sources to public and private could be done later if needed, I don't have a strong opinion here. We may also use TF or other successful modern projects with c++ API as an example. 

Overal, it seems, discussion about public and private interface doesn't block the modernization effort :)

**Comment by prigoyal** [comment]
cool seems like TensorComprehensions.h could be put on back-burner and we can evolve as we progress towards the modernization. As soon as @nicolasvasilache lands the 3 PRs, I'll work on the things created as checklist in this task. Thanks everyone :)

**Comment by prigoyal** [comment]
Hi @salexspb and all, I am hoping to start working on this in various steps. Are there any blocker PRs that you would like to land first? Thank.

**Comment by prigoyal** [comment]
@salexspb the PR for things to do in this issue are out #279 and #284. Please feel free to review whenever you have time. Thanks :)

**Comment by prigoyal** [comment]
both PRs #279 and #284 have been merged now. Please feel free to create new issues around new improvements we should make. Closing out this one as the goals of this task are now finished. :)
