### ISSUE TITLE
[RFC] C++ API refactor towards true backend-agnostic TC: master task

### ISSUE THREAD

**Issue by nicolasvasilache** [facebookresearch/TensorComprehensions#307]
Now that the .cc and .h have been merged in the same repositories, I started a bigger effort to refactor and break the cuda dependency end-to-end. Let's use this task to keep track of the proposed APIs.
I'm adding a larger audience in case people are interested to chime in.

The list of issues is:
- [x] Tensor API #313 (impl in #361)
- [x] High-level compilation API #322 (impl in #359)
- [x] TcExecutor API #323 (impl in #363)
- [x] ATen compiler API #324 (impl in #362)
- [x] Options cache API #339 (impl in #365)
- [x] Multi-backend Autotuner API #342 (impl in #366)
- [x] Multi-backend, multi-search user-facing Autotuner API #345 (impl in #367)
- [x] Drop manual and compilation caches (impl in #353)
- [x] Bring it home #379 

Obsolete:
- [x] ~ExecutionEngine API #309, consensus seems to be towards a more functional-style API, as a consequence ExecutionEngine has died~

**Comment by nicolasvasilache** [comment]
cc @mingzhe09088 @mitmul
